use std::fs;
use std::io::ErrorKind;
use std::path::Path;

use anyhow::{Context, Result};

use super::schema::json_schema_pretty;

pub const CONFIG_SCHEMA_FILE_NAME: &str = "clipboard-transformer.schema.json";

pub const DEFAULT_CONFIG_YAML: &str = r#"# $schema: ./clipboard-transformer.schema.json

# Generated by Clipboard Transformer.
# Edit this file to add, remove, or reorder rules.

config:
  recent_items_count: 5
  max_item_bytes: 104857600
  max_history_bytes: 536870912
  persist_last_clipboard: false
  double_copy_window: 10
  disable_for: 600
  import_refresh_interval: 600
  apps: []
  # Optional explicit editor override for the Edit rule action:
  # editor:
  #   command: code
  #   args: ["--goto", "{file}:{line}:{column}"]

rules:
  - type: url-cleanup
    id: remove-tracking-query-params
    name: Remove tracking parameters
    message: Tracking parameters have been removed
    formats:
      - text
      - url
    remove_query_prefixes:
      - utm_
      - mtm_
      - ga_
      - hmb_
      - itm_
      - otm_
      - mc_
      - vn_
    remove_query_params:
      - Echobox
      - __hsfp
      - __hssc
      - __hstc
      - __s
      - __twitter_impression
      - _ga
      - _gl
      - _openstat
      - action_object_map
      - action_type_map
      - ceneo_spo
      - cmpid
      - fbclid
      - gclid
      - dclid
      - msclkid
      - gbraid
      - wbraid
      - mc_cid
      - mc_eid
      - mc_tc
      - igshid
      - yclid
      - twclid
      - srsltid
      - _hsenc
      - _hsmi
      - mkt_tok
      - ml_subscriber
      - ml_subscriber_hash
      - oly_anon_id
      - oly_enc_id
      - os_ehash
      - rb_clickid
      - s_cid
      - tracking_source
      - vero_conv
      - vero_id
      - wickedid
      - wt_mc
      - wtrid
    remove_query_param_patterns:
      - 'wt_?z?mc'
      - 'ga_[a-z_]+'
      - 'utm(?:_[a-z_]*)?'
      - 'mtm(?:_[a-z_]*)?'
      - 'otm_[a-z_]*'
      - 'vn(?:_[a-z]*)+'

  - type: url-cleanup
    id: remove-youtube-share-token
    name: Remove YouTube share token
    message: YouTube share token has been removed
    formats:
      - text
      - url
    hosts:
      - youtube.com
      - www.youtube.com
      - m.youtube.com
      - youtu.be
    remove_query_params:
      - si

  - type: regexp
    id: youtube-watch-to-shortlink
    name: YouTube watch shortlink
    from: '^(?:https?://)?(?:www\.)?youtube\.com/watch\?v=([A-Za-z0-9_-]{11})(#[^\s]+)?$'
    to: 'https://youtu.be/$1$2'
    message: YouTube watch URL has been shortened
    formats:
      - text
      - url

  - type: regexp
    id: youtube-shorts-to-shortlink
    name: YouTube Shorts shortlink
    from: '^(?:https?://)?(?:www\.)?youtube\.com/shorts/([A-Za-z0-9_-]{11})(?:\?[^#\s]*)?(#[^\s]+)?$'
    to: 'https://youtu.be/$1$2'
    message: YouTube Shorts URL has been shortened
    formats:
      - text
      - url
"#;

pub fn ensure_default_config(path: &Path) -> Result<bool> {
    if path.exists() {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    match fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
    {
        Ok(mut file) => {
            use std::io::Write;
            file.write_all(DEFAULT_CONFIG_YAML.as_bytes())
                .with_context(|| format!("write {}", path.display()))?;
            write_config_schema_next_to(path)?;
            Ok(true)
        }
        Err(error) if error.kind() == ErrorKind::AlreadyExists => Ok(false),
        Err(error) => Err(error).with_context(|| format!("create {}", path.display())),
    }
}

pub fn write_config_schema_next_to(config_path: &Path) -> Result<std::path::PathBuf> {
    let schema_path = config_path
        .parent()
        .unwrap_or(Path::new("."))
        .join(CONFIG_SCHEMA_FILE_NAME);
    write_config_schema(&schema_path)?;
    Ok(schema_path)
}

pub fn sync_config_schema_next_to(config_path: &Path) -> Result<Option<std::path::PathBuf>> {
    let current_schema = json_schema_pretty()?;
    sync_config_schema_contents_next_to(config_path, &current_schema)
}

pub fn sync_config_schema_contents_next_to(
    config_path: &Path,
    current_schema: &str,
) -> Result<Option<std::path::PathBuf>> {
    let schema_path = config_path
        .parent()
        .unwrap_or(Path::new("."))
        .join(CONFIG_SCHEMA_FILE_NAME);
    match fs::read_to_string(&schema_path) {
        Ok(existing_schema) if existing_schema == current_schema => Ok(None),
        Ok(_) => {
            fs::write(&schema_path, current_schema)
                .with_context(|| format!("write {}", schema_path.display()))?;
            Ok(Some(schema_path))
        }
        Err(error) if error.kind() == ErrorKind::NotFound => {
            write_config_schema_contents(&schema_path, current_schema)?;
            Ok(Some(schema_path))
        }
        Err(error) => Err(error).with_context(|| format!("read {}", schema_path.display())),
    }
}

pub fn write_config_schema(path: &Path) -> Result<()> {
    let schema = json_schema_pretty()?;
    write_config_schema_contents(path, &schema)
}

fn write_config_schema_contents(path: &Path, schema: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    fs::write(path, schema).with_context(|| format!("write {}", path.display()))
}
