// @generated by `just gen-icons` from assets/tray.svg; do not edit by hand.
// Included by `platform/tray.rs`, which defines `TrayIconPixels`.
const MACOS_TEMPLATE: TrayIconPixels = TrayIconPixels {
    width: 36,
    height: 36,
    logical_width: 18,
    logical_height: 18,
    format: PixelFormat::GrayAlpha8,
    stride: 36 * 2,
    data: include_bytes!("../../../../assets/generated/tray/macos-template.gray-alpha"),
};
const LIGHT_THEME: TrayIconPixels = TrayIconPixels {
    width: 32,
    height: 32,
    logical_width: 32,
    logical_height: 32,
    format: PixelFormat::Rgba8,
    stride: 32 * 4,
    data: include_bytes!("../../../../assets/generated/tray/light-theme.rgba"),
};
const DARK_THEME: TrayIconPixels = TrayIconPixels {
    width: 32,
    height: 32,
    logical_width: 32,
    logical_height: 32,
    format: PixelFormat::Rgba8,
    stride: 32 * 4,
    data: include_bytes!("../../../../assets/generated/tray/dark-theme.rgba"),
};
