// @generated by `just gen-icons` from assets/tray.svg; do not edit by hand.
// Included by `platform/tray.rs`, which defines `TrayIconPixels`.
const MACOS_TEMPLATE: TrayIconPixels = TrayIconPixels {
    width: 18,
    height: 18,
    rgba: include_bytes!("../../../../assets/generated/tray/macos-template.rgba"),
};
const LIGHT_THEME: TrayIconPixels = TrayIconPixels {
    width: 32,
    height: 32,
    rgba: include_bytes!("../../../../assets/generated/tray/light-theme.rgba"),
};
const DARK_THEME: TrayIconPixels = TrayIconPixels {
    width: 32,
    height: 32,
    rgba: include_bytes!("../../../../assets/generated/tray/dark-theme.rgba"),
};
