//! Rasterizes the canonical tray SVG into committed RGBA artifacts.
//!
//! This used to be a build script in the application graph, which put `resvg`
//! into every build and made the runtime crate read files outside its own
//! package. The pixels are deterministic, so they are generated once, committed,
//! and guarded by [`tests::committed_icons_are_current`].

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use resvg::{tiny_skia, usvg};

use crate::{workspace_root, write_if_changed};

const SOURCE: &str = "assets/tray.svg";
const ARTIFACT_DIR: &str = "assets/generated/tray";
const GENERATED_RUST: &str = "crates/tray/src/native/icons.rs";

/// `(const name, artifact file stem, pixel size, mask color)`
const VARIANTS: [(&str, &str, u32, &str); 3] = [
    ("MACOS_TEMPLATE", "macos-template", 18, "#000000"),
    ("LIGHT_THEME", "light-theme", 32, "#202124"),
    ("DARK_THEME", "dark-theme", 32, "#f1f3f4"),
];

pub fn generate(force: bool) -> Result<()> {
    let root = workspace_root();
    let rust_path = root.join(GENERATED_RUST);

    if !force && rust_path.exists() {
        println!(
            "kept {} (pass --force to re-rasterize)",
            rust_path.display()
        );
        return Ok(());
    }

    for (_, stem, size, color) in VARIANTS {
        let rgba = render_mask(&read_source(&root)?, size, parse_hex_color(color))?;
        write_if_changed(&artifact_path(&root, stem), &rgba)?;
    }
    write_if_changed(&rust_path, rust_source().as_bytes())
}

fn read_source(root: &Path) -> Result<String> {
    let path = root.join(SOURCE);
    std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))
}

fn artifact_path(root: &Path, stem: &str) -> PathBuf {
    root.join(ARTIFACT_DIR).join(format!("{stem}.rgba"))
}

/// The committed Rust shim only carries dimensions and `include_bytes!` paths,
/// so the pixel payload stays out of the source diff.
fn rust_source() -> String {
    let mut generated = String::from(
        "// @generated by `just gen-icons` from assets/tray.svg; do not edit by hand.\n\
         // Included by `platform/tray.rs`, which defines `TrayIconPixels`.\n",
    );
    for (name, stem, size, _) in VARIANTS {
        generated.push_str(&format!(
            "const {name}: TrayIconPixels = TrayIconPixels {{\n    \
             width: {size},\n    height: {size},\n    \
             rgba: include_bytes!(\"../../../../assets/generated/tray/{stem}.rgba\"),\n}};\n"
        ));
    }
    generated
}

fn render_mask(source: &str, size: u32, color: [u8; 3]) -> Result<Vec<u8>> {
    let tree = usvg::Tree::from_str(source, &usvg::Options::default())
        .context("parse canonical tray SVG")?;
    let mut pixmap = tiny_skia::Pixmap::new(size, size).context("allocate tray icon pixmap")?;
    let scale_x = size as f32 / tree.size().width();
    let scale_y = size as f32 / tree.size().height();
    resvg::render(
        &tree,
        tiny_skia::Transform::from_scale(scale_x, scale_y),
        &mut pixmap.as_mut(),
    );
    let mut rgba = pixmap.take();
    for pixel in rgba.chunks_exact_mut(4) {
        if pixel[3] != 0 {
            pixel[..3].copy_from_slice(&color);
        }
    }
    Ok(rgba)
}

fn parse_hex_color(color: &str) -> [u8; 3] {
    let color = color.strip_prefix('#').expect("tray color starts with #");
    assert_eq!(color.len(), 6, "tray color uses six hex digits");
    [
        u8::from_str_radix(&color[0..2], 16).expect("red channel"),
        u8::from_str_radix(&color[2..4], 16).expect("green channel"),
        u8::from_str_radix(&color[4..6], 16).expect("blue channel"),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn committed_icons_are_current() {
        let root = workspace_root();
        let source = read_source(&root).unwrap();
        for (_, stem, size, color) in VARIANTS {
            let expected = render_mask(&source, size, parse_hex_color(color)).unwrap();
            let committed = std::fs::read(artifact_path(&root, stem))
                .unwrap_or_else(|_| panic!("missing {stem}.rgba; run `just gen-icons --force`"));
            assert_eq!(
                committed, expected,
                "{stem}.rgba is stale; run `just gen-icons --force`"
            );
        }
        assert_eq!(
            std::fs::read_to_string(root.join(GENERATED_RUST)).unwrap(),
            rust_source(),
            "run `just gen-icons --force`"
        );
    }

    #[test]
    fn every_variant_fills_a_complete_rgba_buffer() {
        let source = read_source(&workspace_root()).unwrap();
        for (_, _, size, color) in VARIANTS {
            let rgba = render_mask(&source, size, parse_hex_color(color)).unwrap();
            assert_eq!(rgba.len(), (size * size * 4) as usize);
        }
    }
}
