//! Generates repository-only plugin authoring schemas.

use anyhow::{Context, Result};
use ct_plugin_api::PluginManifest;
use schemars::schema_for;
use serde_json::{json, Value};

use crate::{workspace_root, write_if_changed, xtp_schema};

const MANIFEST_SCHEMA_PATH: &str = "plugins/manifest.schema.json";
const PLUGIN_API_SCHEMA_PATH: &str = "plugins/plugin-api-v1.xtp.yaml";
const MANIFEST_SCHEMA_URL: &str =
    "https://raw.githubusercontent.com/jag-k/clipboard-transformer/main/plugins/manifest.schema.json";

pub fn generate() -> Result<()> {
    let repository = workspace_root();
    write_if_changed(
        &repository.join(MANIFEST_SCHEMA_PATH),
        manifest_json_schema()?.as_bytes(),
    )?;
    write_if_changed(
        &repository.join(PLUGIN_API_SCHEMA_PATH),
        xtp_schema::plugin_api_xtp_schema().as_bytes(),
    )?;
    Ok(())
}

fn manifest_json_schema() -> Result<String> {
    let mut schema = serde_json::to_value(schema_for!(PluginManifest))?;
    let root = schema
        .as_object_mut()
        .context("manifest schema root must be an object")?;
    root.insert("$id".to_string(), Value::String(MANIFEST_SCHEMA_URL.into()));
    root.insert(
        "$comment".to_string(),
        Value::String(
            "@generated by `just gen-schemas` (tools/codegen) from the Rust protocol types in crates/plugin-api/src/lib.rs; do not edit by hand."
                .into(),
        ),
    );
    root.insert("additionalProperties".to_string(), Value::Bool(true));
    let properties = root
        .get_mut("properties")
        .and_then(Value::as_object_mut)
        .context("manifest schema properties must be an object")?;
    properties.insert(
        "$schema".to_string(),
        json!({
            "type": "string",
            "format": "uri",
            "description": "Optional editor schema hint. Ignored and not retained by the runtime."
        }),
    );
    set_schema_fields(properties.get_mut("api_version"), &[("const", json!(1))]);
    set_schema_fields(
        properties.get_mut("id"),
        &[("pattern", json!("^[A-Za-z0-9._-]+$"))],
    );
    set_schema_fields(properties.get_mut("name"), &[("pattern", json!("\\S"))]);
    set_schema_fields(properties.get_mut("rules"), &[("minItems", json!(1))]);
    if let Some(rule_properties) = root
        .get_mut("definitions")
        .and_then(Value::as_object_mut)
        .and_then(|definitions| definitions.get_mut("RuleDescriptor"))
        .and_then(Value::as_object_mut)
        .and_then(|rule| rule.get_mut("properties"))
        .and_then(Value::as_object_mut)
    {
        set_schema_fields(
            rule_properties.get_mut("type"),
            &[("pattern", json!("^[A-Za-z0-9._-]+$"))],
        );
    }
    Ok(format!("{}\n", serde_json::to_string_pretty(&schema)?))
}

fn set_schema_fields(schema: Option<&mut Value>, fields: &[(&str, Value)]) {
    let Some(schema) = schema.and_then(Value::as_object_mut) else {
        return;
    };
    for (name, value) in fields {
        schema.insert((*name).to_string(), value.clone());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_manifest_schema_is_current() {
        assert_eq!(
            std::fs::read_to_string(workspace_root().join(MANIFEST_SCHEMA_PATH)).unwrap(),
            manifest_json_schema().unwrap(),
            "run `just gen-schemas`"
        );
    }
}
