use anyhow::{anyhow, Result};
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString, NSWorkspace};
use objc2_foundation::{NSData, NSString};
use std::collections::BTreeSet;

use crate::{format_requests_native_kind, ClipboardBackend, ClipboardMetadata};
use crate::{
    ClipboardFormat, ClipboardItem, ClipboardPlatform, ClipboardSourceApp, NativeRepresentation,
};

const SOURCE_MARKER_TYPE: &str = "org.nspasteboard.source";
const SOURCE_MARKER_VALUE: &[u8] = b"dev.jag-k.clipboard-transformer";
const IGNORED_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
    "net.antelle.keeweb",
    SOURCE_MARKER_TYPE,
];

pub struct MacosClipboardBackend;

impl MacosClipboardBackend {
    pub fn new() -> Result<Self> {
        Ok(Self)
    }
}

impl ClipboardBackend for MacosClipboardBackend {
    fn change_count(&mut self) -> Result<Option<u64>> {
        Ok(Some(read_change_count()))
    }

    fn read(&mut self) -> Result<Option<ClipboardItem>> {
        read_item(0)
    }

    fn read_limited(&mut self, max_bytes: u64) -> Result<Option<ClipboardItem>> {
        read_item(max_bytes)
    }

    fn read_formats_limited(
        &mut self,
        formats: &BTreeSet<ClipboardFormat>,
        max_bytes: u64,
    ) -> Result<Option<ClipboardItem>> {
        let pasteboard = NSPasteboard::generalPasteboard();
        let Some(types) = pasteboard.types() else {
            return Ok(None);
        };
        read_item_from_pasteboard(&pasteboard, &types, max_bytes, Some(formats))
    }

    fn metadata(&mut self) -> Result<ClipboardMetadata> {
        let pasteboard = NSPasteboard::generalPasteboard();
        let Some(types) = pasteboard.types() else {
            return Ok(ClipboardMetadata::readable(None));
        };
        if types.iter().any(|data_type| is_ignored_type(&data_type)) {
            log::info!("clipboard item ignored from native type markers");
            return Ok(ClipboardMetadata::ignored());
        }
        Ok(ClipboardMetadata::readable(frontmost_app()))
    }

    fn write(&mut self, content: &ClipboardItem) -> Result<()> {
        write_item(content)
    }
}

fn read_change_count() -> u64 {
    NSPasteboard::generalPasteboard().changeCount() as u64
}

fn read_item(max_bytes: u64) -> Result<Option<ClipboardItem>> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let Some(types) = pasteboard.types() else {
        return Ok(None);
    };
    read_item_from_pasteboard(&pasteboard, &types, max_bytes, None)
}

fn read_item_from_pasteboard(
    pasteboard: &NSPasteboard,
    types: &objc2_foundation::NSArray<objc2_foundation::NSString>,
    max_bytes: u64,
    formats: Option<&BTreeSet<ClipboardFormat>>,
) -> Result<Option<ClipboardItem>> {
    let mut content = ClipboardItem::for_platform(ClipboardPlatform::Macos);
    let mut total_bytes = 0u128;
    for data_type in types.iter() {
        if formats
            .is_some_and(|formats| !format_requests_native_kind(formats, &data_type.to_string()))
        {
            continue;
        }
        if let Some(data) = pasteboard.dataForType(&data_type) {
            total_bytes = total_bytes.saturating_add(data.len() as u128);
            if max_bytes > 0 && total_bytes > u128::from(max_bytes) {
                log::info!("clipboard item ignored while reading size_bytes>{max_bytes}");
                return Ok(None);
            }
            content.set_native(NativeRepresentation::named(
                data_type.to_string(),
                data.to_vec(),
            ));
        }
    }

    // AppKit's string conversion is authoritative even when the native data
    // representation uses a legacy encoding.
    let reads_text = formats.is_none_or(|formats| {
        format_requests_native_kind(formats, &unsafe { NSPasteboardTypeString }.to_string())
    });
    if reads_text {
        if let Some(text) = pasteboard.stringForType(unsafe { NSPasteboardTypeString }) {
            content.set_derived_text(
                text.to_string(),
                vec![unsafe { NSPasteboardTypeString }.to_string()],
            );
        }
    }
    derive_macos_semantics(pasteboard, &mut content);
    if max_bytes > 0 && content.size_bytes() as u128 > u128::from(max_bytes) {
        log::info!("clipboard item ignored after text conversion size_bytes>{max_bytes}");
        return Ok(None);
    }
    let has_content = formats.map_or_else(
        || !content.representations().is_empty(),
        |formats| formats.iter().any(|format| content.bytes(format).is_some()),
    );
    if !has_content {
        return Ok(None);
    }
    if let Some(source_app) = frontmost_app() {
        content = content.with_source_app(source_app);
    }
    Ok(Some(content))
}

fn frontmost_app() -> Option<ClipboardSourceApp> {
    let app = NSWorkspace::sharedWorkspace().frontmostApplication()?;
    let bundle_id = app.bundleIdentifier().map(|value| value.to_string());
    let name = app.localizedName().map(|value| value.to_string());
    if bundle_id.is_none() && name.is_none() {
        None
    } else {
        Some(ClipboardSourceApp::new(bundle_id, name))
    }
}

fn write_item(content: &ClipboardItem) -> Result<()> {
    let pasteboard = NSPasteboard::generalPasteboard();
    write_item_to_pasteboard(&pasteboard, content)
}

fn write_item_to_pasteboard(pasteboard: &NSPasteboard, content: &ClipboardItem) -> Result<()> {
    pasteboard.clearContents();

    let marker_type = objc2_foundation::NSString::from_str(SOURCE_MARKER_TYPE);
    let marker = NSData::with_bytes(SOURCE_MARKER_VALUE);
    if !pasteboard.setData_forType(Some(&marker), &marker_type) {
        return Err(anyhow!("NSPasteboard rejected source marker"));
    }

    let mut wrote_any = false;
    for representation in content.representations() {
        if stale_for_authored_semantic(content, representation.kind()) {
            continue;
        }
        let data_type = NSString::from_str(representation.kind());
        let data = NSData::with_bytes(representation.data());
        if pasteboard.setData_forType(Some(&data), &data_type) {
            wrote_any = true;
        } else {
            return Err(anyhow!(
                "NSPasteboard rejected {} representation",
                representation.kind()
            ));
        }
    }

    for (semantic, data_type) in [
        (
            content.text_semantic(),
            unsafe { NSPasteboardTypeString }.to_string(),
        ),
        (content.url_semantic(), "public.url".to_string()),
        (content.file_url_semantic(), "public.file-url".to_string()),
        (content.html_semantic(), "public.html".to_string()),
        (content.rtf_semantic(), "public.rtf".to_string()),
    ] {
        let Some(semantic) = semantic.filter(|semantic| semantic.is_authored()) else {
            continue;
        };
        let data_type = NSString::from_str(&data_type);
        let value = NSString::from_str(semantic.value());
        if !pasteboard.setString_forType(&value, &data_type) {
            return Err(anyhow!(
                "NSPasteboard rejected authored {} representation",
                data_type
            ));
        }
        wrote_any = true;
    }

    wrote_any
        .then_some(())
        .ok_or_else(|| anyhow!("clipboard item has no representations"))
}

fn derive_macos_semantics(pasteboard: &NSPasteboard, content: &mut ClipboardItem) {
    for (kind, set) in [
        (
            "public.url",
            ClipboardItem::set_derived_url as fn(&mut ClipboardItem, String, Vec<String>),
        ),
        (
            "public.html",
            ClipboardItem::set_derived_html as fn(&mut ClipboardItem, String, Vec<String>),
        ),
        (
            "public.rtf",
            ClipboardItem::set_derived_rtf as fn(&mut ClipboardItem, String, Vec<String>),
        ),
        (
            "public.file-url",
            ClipboardItem::set_derived_file_url as fn(&mut ClipboardItem, String, Vec<String>),
        ),
    ] {
        if content.representation(kind).is_none() {
            continue;
        }
        let data_type = NSString::from_str(kind);
        if let Some(value) = pasteboard.stringForType(&data_type) {
            set(content, value.to_string(), vec![kind.to_string()]);
        }
    }
}

fn stale_for_authored_semantic(content: &ClipboardItem, kind: &str) -> bool {
    match kind {
        "public.utf8-plain-text" | "public.utf16-plain-text" | "NSStringPboardType" => content
            .text_semantic()
            .is_some_and(|semantic| semantic.is_authored()),
        "public.url" => content
            .url_semantic()
            .is_some_and(|semantic| semantic.is_authored()),
        "public.file-url" => content
            .file_url_semantic()
            .is_some_and(|semantic| semantic.is_authored()),
        "public.html" => content
            .html_semantic()
            .is_some_and(|semantic| semantic.is_authored()),
        "public.rtf" => content
            .rtf_semantic()
            .is_some_and(|semantic| semantic.is_authored()),
        _ => false,
    }
}

fn is_ignored_type(data_type: &objc2_foundation::NSString) -> bool {
    IGNORED_TYPES.contains(&data_type.to_string().as_str())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hygiene_list_covers_own_sensitive_and_transient_markers() {
        for data_type in [
            SOURCE_MARKER_TYPE,
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "com.agilebits.onepassword",
            "net.antelle.keeweb",
        ] {
            assert!(is_ignored_type(&objc2_foundation::NSString::from_str(
                data_type
            )));
        }
        assert!(!is_ignored_type(&objc2_foundation::NSString::from_str(
            "public.utf8-plain-text"
        )));
    }

    #[test]
    fn named_pasteboard_round_trip_preserves_native_bytes_and_authored_text() {
        let name = NSString::from_str("dev.jag-k.clipboard-transformer.tests.native-item");
        let pasteboard = NSPasteboard::pasteboardWithName(&name);
        let mut item = ClipboardItem::for_platform(ClipboardPlatform::Macos);
        item.set_native(NativeRepresentation::named(
            "com.example.binary",
            vec![0, 1, 0xff],
        ));
        item.set_text("hello from AppKit");
        item.set_file_url("file:///tmp/example.txt");

        write_item_to_pasteboard(&pasteboard, &item).unwrap();

        let binary_type = NSString::from_str("com.example.binary");
        assert_eq!(
            pasteboard.dataForType(&binary_type).unwrap().to_vec(),
            [0, 1, 0xff]
        );
        assert_eq!(
            pasteboard
                .stringForType(unsafe { NSPasteboardTypeString })
                .unwrap()
                .to_string(),
            "hello from AppKit"
        );

        let types = pasteboard.types().unwrap();
        let restored = read_item_from_pasteboard(&pasteboard, &types, 1024 * 1024, None)
            .unwrap()
            .unwrap();
        assert_eq!(restored.platform(), ClipboardPlatform::Macos);
        assert_eq!(restored.text(), Some("hello from AppKit"));
        assert_eq!(restored.file_url(), Some("file:///tmp/example.txt"));
        assert_eq!(
            restored
                .representation("com.example.binary")
                .unwrap()
                .data(),
            [0, 1, 0xff]
        );
    }
}
