// THIS FILE WAS GENERATED BY `xtp-rust-bindgen`. DO NOT EDIT.

#![allow(non_snake_case)]
#![allow(unused_macros)]
use extism_pdk::*;

#[allow(unused)]
fn panic_if_key_missing() -> ! {
    panic!("missing key");
}

pub(crate) mod internal {
    pub(crate) fn return_error(e: extism_pdk::Error) -> i32 {
        let err = format!("{:?}", e);
        let mem = extism_pdk::Memory::from_bytes(&err).unwrap();
        unsafe {
            extism_pdk::extism::error_set(mem.offset());
        }
        -1
    }
}

#[allow(unused)]
macro_rules! try_input {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(x) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

#[allow(unused)]
macro_rules! try_input_json {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(extism_pdk::Json(x)) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

use base64_serde::base64_serde_type;

base64_serde_type!(Base64Standard, base64::engine::general_purpose::STANDARD);

mod exports {
    use super::*;

    #[no_mangle]
    pub extern "C" fn compile_rule() -> i32 {
        let ret = crate::compile_rule(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn initialize() -> i32 {
        let ret = crate::initialize(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn transform() -> i32 {
        let ret = crate::transform(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }
}

pub mod types {
    use super::*;

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct ClipboardSourceApp {
        #[serde(rename = "bundle_id")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub bundle_id: Option<String>,

        #[serde(rename = "name")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub name: Option<String>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct CompileRuleRequest {
        /// Local rule type name.
        #[serde(rename = "rule_type")]
        pub rule_type: String,

        /// Rule settings: every configured key except the shared rule fields.
        #[serde(rename = "settings")]
        pub settings: serde_json::Map<String, serde_json::Value>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct CompileRuleResponse {
        /// Why the rule settings were rejected.
        #[serde(rename = "message")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub message: Option<String>,

        /// Discriminant: "ok" or "error".
        #[serde(rename = "result")]
        pub result: types::CompileRuleResult,

        /// Opaque compiled rule value, echoed back on transform.
        #[serde(rename = "rule")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub rule: Option<serde_json::Map<String, serde_json::Value>>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub enum CompileRuleResult {
        #[default]
        #[serde(rename = "ok")]
        Ok,
        #[serde(rename = "error")]
        Error,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct GrantedCapabilities {
        /// Whether environment expansion ran over the plugin settings.
        #[serde(rename = "env_expansion")]
        pub env_expansion: bool,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct InitializeRequest {
        #[serde(rename = "api_version")]
        pub api_version: i64,

        #[serde(rename = "granted_capabilities")]
        pub granted_capabilities: types::GrantedCapabilities,

        /// Resolved opaque plugin settings (after any granted env expansion).
        #[serde(rename = "settings")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub settings: Option<serde_json::Map<String, serde_json::Value>>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct InitializeResponse {
        /// Available rule type names (local, un-namespaced). `None` means every declared rule type is available.
        #[serde(rename = "available_rules")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub available_rules: Option<Vec<String>>,

        #[serde(rename = "issues")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub issues: Option<Vec<types::PluginIssue>>,

        #[serde(rename = "status")]
        pub status: types::PluginHealth,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub enum IssueSeverity {
        #[default]
        #[serde(rename = "warning")]
        Warning,
        #[serde(rename = "error")]
        Error,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub enum PluginHealth {
        #[default]
        #[serde(rename = "operational")]
        Operational,
        #[serde(rename = "degraded")]
        Degraded,
        #[serde(rename = "blocked")]
        Blocked,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PluginIssue {
        /// Whether user action is needed: `none`, `informational`, or `action-required`.
        #[serde(rename = "attention")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub attention: Option<String>,

        /// Stable machine-readable code.
        #[serde(rename = "code")]
        pub code: String,

        #[serde(rename = "details")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub details: Option<String>,

        /// Affected local rule type names.
        #[serde(rename = "rule_types")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub rule_types: Option<Vec<String>>,

        /// Path inside the plugin settings this issue refers to.
        #[serde(rename = "setting_path")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub setting_path: Option<String>,

        #[serde(rename = "severity")]
        pub severity: types::IssueSeverity,

        #[serde(rename = "summary")]
        pub summary: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TransformRequest {
        /// Selected clipboard format id.
        #[serde(rename = "format")]
        pub format: String,

        /// Opaque compiled rule value returned by `compile_rule`.
        #[serde(rename = "rule")]
        pub rule: serde_json::Map<String, serde_json::Value>,

        /// Local rule type name.
        #[serde(rename = "rule_type")]
        pub rule_type: String,

        /// Best-effort source application metadata.
        #[serde(rename = "source_app")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub source_app: Option<types::ClipboardSourceApp>,

        /// Selected UTF-8 representation.
        #[serde(rename = "value")]
        pub value: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TransformResponse {
        /// Discriminant: "no-match" or "replace".
        ///
        /// This stays a string because the XTP Rust generator rejects hyphenated enum values as source-language identifiers.
        #[serde(rename = "action")]
        pub action: String,

        /// Optional notification body.
        #[serde(rename = "message")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub message: Option<String>,

        /// Authored plain text. Stale textual representations are removed while unrelated native payloads remain unchanged.
        #[serde(rename = "text")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub text: Option<String>,
    }
}

mod raw_imports {
    use super::*;
    #[host_fn]
    extern "ExtismHost" {

        pub(crate) fn http_host_allowed(input: String) -> Json<bool>;

    }
}

/// http_host_allowed Return whether one literal hostname is allowed by the host-owned Extism HTTP policy. Glob input is rejected.
#[allow(unused)]
pub(crate) fn http_host_allowed(input: String) -> std::result::Result<bool, extism_pdk::Error> {
    let res = unsafe { raw_imports::http_host_allowed(input)? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}
